spring.application.name=Portfolio-Manager
spring.datasource.url=jdbc:mysql://localhost:3306/portfolio_manager

spring.datasource.username=root

spring.datasource.password=n3u3da!
spring.flyway.baseline-on-migrate=true

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true


spring.flyway.enabled=true
